version: '2.1'
services:
  bills:
    image: "faseldi/billsx64"
    network_mode: "host"
    ports:
      - "9091:9091"
    expose:
      - "9091"
    environment:
      - CONSUL_CLIENT=10.226.160.80
    depends_on:
      consul-kv:
        condition: service_healthy
  bills-db:
    image: "sameersbn/mongodb:latest"
    network_mode: "host"
    ports:
      - "27017:27017"
  products:
    image: "faseldi/productsx64"
    network_mode: "host"
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      - CONSUL_CLIENT=10.226.160.80
    depends_on:
      consul-kv:
        condition: service_healthy
  products-db:
    image: "faseldi/products-dbx64"
    network_mode: "host"
    ports:
      - "5432:5432"
    expose:
      - "5432"
  customers:
    image: "lechelong/customersx64"
    network_mode: "host"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - CONSUL_CLIENT=10.226.160.80:8500
    depends_on:
      consul-kv:
        condition: service_healthy
  carts:
    image: "lechelong/cartsx64"
    network_mode: "host"
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - CONSUL_CLIENT=10.226.160.80:8500
    depends_on:
      consul-kv:
        condition: service_healthy
  carts-db:
    image: "lechelong/carts-dbx64"
    network_mode: "host"
    ports:
      - "6379:6379"
    expose:
      - "6379"
  gateway:
    image: "lechelong/gatewayx64"
    network_mode: "host"
    ports:
      - "9090:9090"
    expose:
      - "9090"
    depends_on:
      consul-kv:
        condition: service_healthy
  consul:
    image: "lechelong/consulx64"
    ports:
      - "8500:8500"
    expose:
      - "8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/ui"]
      interval: 5s
      timeout: 1s
      retries: 100
  consul-kv:
    image: "lechelong/consul-kv"
    network_mode: "host"
    depends_on:
      - "consul"
    healthcheck:
      test: "exit 0"
